version: "3.9"

services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgres
    restart: unless-stopped
    ports:
     - "5432:5432"
    volumes:
      - "./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf"
      - "./postgresql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres