apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-app-deployment
  labels:
    app: e-commerce-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: e-commerce-app
  template:
    metadata:
      labels:
        app: e-commerce-app
    spec:
      containers:
        - name: e-commerce-app
          image: jpaezr/e-commerce-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
